name: Puppet Lint
on:
  push:
    branches: [ master ]
    paths:
      - '**.pp'
      - '.github/**'

  pull_request:
    branches: [ master ]
    paths:
      - '**.pp'
      - '.github/**'

jobs:
  puppet-lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: puppet-lint
      continue-on-error: true
      uses: scottbrenner/puppet-lint-action@master
      with:
        args: --no-80chars-check --no-140chars-check --no-puppet_url_without_modules-check --no-documentation-check --no-variable_scope-check ./

  notify-irc:
    needs: puppet-lint
    runs-on: ubuntu-latest
    if: ${{ always() && github.repository_owner == 'WikiForge' && ( github.ref	== 'refs/heads/master' || github.event_name == 'pull_request' ) }}
    steps:
      - name: failed
        uses: technote-space/workflow-conclusion-action@v3
      - uses: rectalogic/notify-irc@v2
        if: env.WORKFLOW_CONCLUSION == 'failure'
        with:
          channel: "#wikiforge-sre"
          server: "irc.libera.chat"
          nickname: wikiforge-github
          message: ${{ github.repository }} - ${{ github.actor }} the build has errored.
          sasl_password: ${{ secrets.IRC_WIKIFORGEBOTS }}
