name: Check Python
on:
  push:
    paths:
      - '**.py'
      - '.github/**'

  pull_request:
    paths:
      - '**.py'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }} 
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libgnutls28-dev
          pip install -U pip
          pip install -r .github/pythonchecks.txt
      - name: Run tests
        run: |
          flake8 modules/mediawiki modules/ssl --ignore=E501,W503,SFS301,T003,PT009
          coverage run --branch -m pytest modules
          mypy modules/mediawiki modules/ssl --ignore-missing-imports

  notify-irc:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ always() && github.repository_owner == 'WikiForge' && ( github.ref	== 'refs/heads/master' || github.event_name == 'pull_request' ) }}
    steps:
      - name: succeeded
        uses: technote-space/workflow-conclusion-action@v3
      - uses: rectalogic/notify-irc@v2
        if: env.WORKFLOW_CONCLUSION == 'success'
        with:
          channel: "#wikiforge-sre"
          server: "irc.libera.chat"
          nickname: wikiforge-github
          message: ${{ github.repository }} - ${{ github.actor }} the build passed.
          sasl_password: ${{ secrets.IRC_WIKIFORGEBOTS }}

      - name: failed
        uses: technote-space/workflow-conclusion-action@v3
      - uses: rectalogic/notify-irc@v2
        if: env.WORKFLOW_CONCLUSION == 'failure'
        with:
          channel: "#wikiforge-sre"
          server: "irc.libera.chat"
          nickname: wikiforge-github
          message: ${{ github.repository }} - ${{ github.actor }} the build has errored.
          sasl_password: ${{ secrets.IRC_WIKIFORGEBOTS }}
