name: Check for Typos
on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run typos
        continue-on-error: true
        run: |
           ! grep -E -r --binary-files=without-match --color=always --file=typos --exclude=typos --exclude-dir=.git

  notify-irc:
    needs: check
    runs-on: ubuntu-latest
    if: ${{ always() && github.repository_owner == 'WikiTideOrg' && ( github.ref	== 'refs/heads/master' || github.event_name == 'pull_request' ) }}
    steps:
      - name: failed
        uses: technote-space/workflow-conclusion-action@v3
      - uses: rectalogic/notify-irc@v2
        if: env.WORKFLOW_CONCLUSION == 'failure'
        with:
          channel: "#wikitide-sre"
          server: "irc.libera.chat"
          nickname: wikitide-github
          message: ${{ github.repository }} - ${{ github.actor }} the build has errored.
          sasl_password: ${{ secrets.IRC_WIKITIDEBOTS }}
